# Computation with multiple methods

The workspace at the link below has a notebook with which you will analyze some data from a (fictional) course at NYU. The data records the scores of each of 48 students on some assessments:

- the first 5 columns are lab assignment grades
- the next 8 columns are problem set grades
- the next column is a midterm exam
- the last column is a final exam

The course instructor wants to compute an overall numeric grade out of 100 for each student according to multiple methods, as follows:

- `Method A`: 25% lab assignment average, 25% problem set average, 25% midterm, 25% final
- `Method B`: 20% lab assignment average, 20% problem set average, 30% midterm, 30% final
- `Method C`: 30% lab assignment average, 30% problem set average, 20% midterm, 20% final
- `Method D`: 20% lab assignment average, 20% problem set average, 20% midterm, 40% final

Then, the student's overall course grade will be computed as the highest of these four values.

For full credit, implement your solution without any explicit `for` loops (or other control structures). Also, for full credit, your code should use the following `numpy` functions: `max`, `argmax`, and any one of the following: `stack`, `vstack`, `hstack`, `column_stack`, or `row_stack`.


| Name |	Type |	Description |
| --- | --- | --- |
|`grades_all_methods` |	2d numpy array |	This array should have 48 rows and 4 columns, representing the students' grades according to each of the four methods, respectively.|
|`grades` |	1d numpy array |	Per-student overall course grade.|
|`idx_method` | 	1d numpy array	| Index of the method that realizes the highest grade for this student (0 for Method A, 1 for Method B, 2 for Method C, and 3 for Method D).|


In [1]:
import numpy as np

Read in the data to a `numpy` array in `x`. If you want to, you can add code to the following cell to explore `x` (for example, see its shape).


In [2]:
x = np.genfromtxt('data.csv',delimiter=',')

Write code to compute the following arrays:

* `grades_all_methods` - student grades according to each of the four different methods (first column: Method A, second column: Method B, third column: Method C, fourth column: method D).
* `grades` - student grades using "best of four methods".
* `idx_method` - the index of the grading method that realizes the highest grade for each student (0 for Method A, 1 for Method B, 2 for Method C, and 3 for Method D).

In [3]:
#grade (write your code in this cell and DO NOT DELETE THIS LINE)
A = 0.25 * np.mean(x[:, :5], axis=1) + 0.25 * np.mean(x[:, 5:13], axis=1) + 0.25 * np.mean(x[:, 13:14], axis=1) + 0.25 * np.mean(x[:, 14:], axis=1)
B = 0.20 * np.mean(x[:, :5], axis=1) + 0.20 * np.mean(x[:, 5:13], axis=1) + 0.30 * np.mean(x[:, 13:14], axis=1) + 0.30 * np.mean(x[:, 14:], axis=1)
C = 0.30 * np.mean(x[:, :5], axis=1) + 0.30 * np.mean(x[:, 5:13], axis=1) + 0.20 * np.mean(x[:, 13:14], axis=1) + 0.20 * np.mean(x[:, 14:], axis=1)
D = 0.20 * np.mean(x[:, :5], axis=1) + 0.20 * np.mean(x[:, 5:13], axis=1) + 0.20 * np.mean(x[:, 13:14], axis=1) + 0.40 * np.mean(x[:, 14:], axis=1)
A = np.reshape(A, (48, 1))
B = np.reshape(B, (48, 1))
C = np.reshape(C, (48, 1))
D = np.reshape(D, (48, 1))
grades_all_methods = np.hstack((A, B, C, D))
grades = np.max(grades_all_methods, axis=1)
idx_method = np.argmax(grades_all_methods, axis=1)

You can test your work by looking at the output in the next cells (which you can also modify as you like - these cells will not be graded):

In [4]:
grades_all_methods

array([[75.38125, 76.305  , 74.4575 , 76.505  ],
       [68.     , 67.     , 69.     , 70.4    ],
       [69.11875, 68.895  , 69.3425 , 69.295  ],
       [67.25   , 67.2    , 67.3    , 68.4    ],
       [59.54375, 58.035  , 61.0525 , 58.435  ],
       [69.0875 , 68.47   , 69.705  , 72.07   ],
       [65.21875, 64.675  , 65.7625 , 67.775  ],
       [73.5875 , 73.87   , 73.305  , 74.67   ],
       [73.05   , 73.24   , 72.86   , 75.04   ],
       [75.375  , 76.9    , 73.85   , 77.9    ],
       [63.3    , 62.84   , 63.76   , 61.64   ],
       [68.78125, 68.325  , 69.2375 , 66.625  ],
       [71.2875 , 70.33   , 72.245  , 71.23   ],
       [66.7875 , 66.63   , 66.945  , 68.63   ],
       [62.3375 , 60.97   , 63.705  , 62.27   ],
       [69.25   , 68.7    , 69.8    , 70.     ],
       [62.63125, 60.705  , 64.5575 , 60.705  ],
       [72.00625, 71.905  , 72.1075 , 74.805  ],
       [66.84375, 66.475  , 67.2125 , 69.275  ],
       [70.19375, 70.555  , 69.8325 , 72.755  ],
       [70.7    , 70

In [5]:
grades

array([76.505 , 70.4   , 69.3425, 68.4   , 61.0525, 72.07  , 67.775 ,
       74.67  , 75.04  , 77.9   , 63.76  , 69.2375, 72.245 , 68.63  ,
       63.705 , 70.    , 64.5575, 74.805 , 69.275 , 72.755 , 71.14  ,
       68.64  , 78.535 , 68.435 , 71.52  , 70.34  , 70.5075, 69.3475,
       72.045 , 73.905 , 75.6   , 75.66  , 70.435 , 65.93  , 76.48  ,
       60.7375, 71.44  , 67.475 , 61.18  , 77.115 , 70.96  , 66.725 ,
       75.92  , 67.875 , 70.91  , 69.3125, 73.06  , 69.245 ])

In [6]:
idx_method

array([3, 3, 2, 3, 2, 3, 3, 3, 3, 3, 2, 2, 2, 3, 2, 3, 2, 3, 3, 3, 2, 2,
       3, 3, 2, 3, 2, 2, 1, 1, 3, 3, 3, 2, 1, 2, 1, 1, 2, 3, 2, 3, 3, 2,
       3, 2, 1, 3], dtype=int64)